/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package RacunalniServis.view;

/**
 *
 * @author Matej
 */
public class GlavniIzbornik extends javax.swing.JFrame {

    /**
     * Creates new form Izvjestaji
     */
    public GlavniIzbornik() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel2 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        btnKlijent = new javax.swing.JButton();
        btnNarudzba = new javax.swing.JButton();
        btnRacun = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jLabel4 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setPreferredSize(new java.awt.Dimension(639, 490));
        getContentPane().setLayout(null);

        jLabel2.setBackground(new java.awt.Color(255, 255, 255));
        jLabel2.setFont(new java.awt.Font("Times New Roman", 1, 24)); // NOI18N
        jLabel2.setText(" RAČUNALNI SERVIS      \"QUICK\" ");
        jLabel2.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED, new java.awt.Color(0, 153, 255), new java.awt.Color(0, 153, 255), new java.awt.Color(0, 153, 255), new java.awt.Color(0, 153, 255)));
        getContentPane().add(jLabel2);
        jLabel2.setBounds(110, 20, 400, 50);
        jLabel2.setOpaque(true);

        jLabel1.setBackground(new java.awt.Color(255, 255, 255));
        jLabel1.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        jLabel1.setText(" Glavni izbornik");
        jLabel1.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED, new java.awt.Color(0, 153, 255), new java.awt.Color(0, 153, 255), new java.awt.Color(0, 153, 255), new java.awt.Color(0, 153, 255)));
        getContentPane().add(jLabel1);
        jLabel1.setBounds(230, 70, 140, 30);
        jLabel1.setOpaque(true);

        btnKlijent.setText("Unos i izmjena klijenta");
        btnKlijent.setMaximumSize(new java.awt.Dimension(149, 23));
        btnKlijent.setMinimumSize(new java.awt.Dimension(149, 23));
        btnKlijent.setPreferredSize(new java.awt.Dimension(149, 23));
        btnKlijent.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnKlijentActionPerformed(evt);
            }
        });
        getContentPane().add(btnKlijent);
        btnKlijent.setBounds(190, 140, 220, 50);

        btnNarudzba.setText("Unos i izmjena narudžbe");
        btnNarudzba.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnNarudzbaActionPerformed(evt);
            }
        });
        getContentPane().add(btnNarudzba);
        btnNarudzba.setBounds(190, 220, 220, 50);

        btnRacun.setText("Izdavanje računa");
        btnRacun.setMaximumSize(new java.awt.Dimension(149, 23));
        btnRacun.setMinimumSize(new java.awt.Dimension(149, 23));
        btnRacun.setPreferredSize(new java.awt.Dimension(149, 23));
        btnRacun.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnRacunActionPerformed(evt);
            }
        });
        getContentPane().add(btnRacun);
        btnRacun.setBounds(190, 300, 220, 50);

        jButton2.setText("Administrator");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton2);
        jButton2.setBounds(480, 405, 130, 30);

        jLabel4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/RacunalniServis/view/most_beautiful_bridge_on_earth-wallpaper-1920x1080.jpg"))); // NOI18N
        jLabel4.setText("jLabel4");
        jLabel4.setPreferredSize(new java.awt.Dimension(640, 460));
        getContentPane().add(jLabel4);
        jLabel4.setBounds(0, 0, 640, 460);

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void btnKlijentActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnKlijentActionPerformed
        // TODO add your handling code here:
        Klijenti klijent = new Klijenti();
        klijent.setVisible(true);
        setVisible(false);
        dispose();
    }//GEN-LAST:event_btnKlijentActionPerformed

    private void btnNarudzbaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnNarudzbaActionPerformed
        // TODO add your handling code here:
        UnosNarudzbe narudzba = new UnosNarudzbe();
        narudzba.setVisible(true);
        setVisible(false);
        dispose();
    }//GEN-LAST:event_btnNarudzbaActionPerformed

    private void btnRacunActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRacunActionPerformed
        // TODO add your handling code here:
        Racun racun = new Racun();
        racun.setVisible(true);
        setVisible(false);
        dispose();
    }//GEN-LAST:event_btnRacunActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        // TODO add your handling code here:
        Autentikacija aut = new Autentikacija();
        aut.setVisible(true);
        setVisible(false);
        dispose();
    }//GEN-LAST:event_jButton2ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(GlavniIzbornik.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(GlavniIzbornik.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(GlavniIzbornik.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(GlavniIzbornik.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new GlavniIzbornik().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnKlijent;
    private javax.swing.JButton btnNarudzba;
    private javax.swing.JButton btnRacun;
    private javax.swing.JButton jButton2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel4;
    // End of variables declaration//GEN-END:variables
}
