/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package RacunalniServis.view;

import RacunalniServis.controller.SQLController;
import RacunalniServis.model.Klijent;
import RacunalniServis.model.Narudzba;
import RacunalniServis.model.Usluge;
import static java.awt.image.ImageObserver.WIDTH;
import java.util.ArrayList;

/**
 *
 * @author Matej
 */
public class UnosNarudzbe extends javax.swing.JFrame {

    ArrayList<Klijent> klijenti  = new ArrayList();
    ArrayList<Usluge> usluge  = new ArrayList();
    SQLController db = new SQLController();
    /**
     * Creates new form Usluge
     */
    public Narudzba order = new Narudzba();
    
    public UnosNarudzbe() {
        initComponents();
        this.klijenti = db.listaKlijenta();
        this.usluge = db.listaUsluga();
        if(this.klijenti == null || this.usluge == null)
            return;
        
        for(int i=0;i<this.klijenti.size();i++){
            Klijent klijent = this.klijenti.get(i);
          
            clientList.addItem(klijent);
        }
        for(int i=0;i<this.usluge.size();i++){
            Usluge u = this.usluge.get(i);
           
            uslugeList.addItem(u);
        }
    }

    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        uslugeList = new javax.swing.JComboBox<>();
        jScrollPane1 = new javax.swing.JScrollPane();
        txtNarudzba = new javax.swing.JTextArea();
        btnPotvrda = new javax.swing.JButton();
        btnIzmjena = new javax.swing.JButton();
        jLabel4 = new javax.swing.JLabel();
        clientList = new javax.swing.JComboBox<>();
        btnOdustani = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel1.setText("Unos i izmjena narudžbe");

        uslugeList.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                uslugeListActionPerformed(evt);
            }
        });

        txtNarudzba.setColumns(20);
        txtNarudzba.setRows(5);
        jScrollPane1.setViewportView(txtNarudzba);

        btnPotvrda.setText("Potvrda narudžbe");
        btnPotvrda.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnPotvrdaActionPerformed(evt);
            }
        });

        btnIzmjena.setText("Izmjena narudžbe");

        jLabel4.setText("Klijent");

        clientList.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                clientListActionPerformed(evt);
            }
        });

        btnOdustani.setText("Odustani");
        btnOdustani.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnOdustaniActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(65, 65, 65)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addComponent(btnIzmjena)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(btnPotvrda))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(uslugeList, javax.swing.GroupLayout.PREFERRED_SIZE, 170, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(23, 23, 23)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(btnOdustani)
                                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 273, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(184, 184, 184)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel4)
                                .addGap(18, 18, 18)
                                .addComponent(clientList, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(jLabel1))))
                .addContainerGap(65, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(30, 30, 30)
                .addComponent(jLabel1)
                .addGap(46, 46, 46)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(clientList, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(77, 77, 77)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 140, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(uslugeList, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(6, 6, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnIzmjena)
                    .addComponent(btnPotvrda))
                .addGap(34, 34, 34)
                .addComponent(btnOdustani)
                .addGap(30, 30, 30))
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void clientListActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_clientListActionPerformed
        Klijent selected = (Klijent)this.clientList.getSelectedItem();
        System.out.println(selected.getSifraKlijenta());
        this.order.setKlijent(selected.getSifraKlijenta());
    }//GEN-LAST:event_clientListActionPerformed

    private void btnOdustaniActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnOdustaniActionPerformed
        // TODO add your handling code here:
        GlavniIzbornik glavniFrame = new GlavniIzbornik();
        glavniFrame.setVisible(true);
        setVisible(false);
        dispose();
    }//GEN-LAST:event_btnOdustaniActionPerformed

    private void ispisiNarudzbu(){
        String text;
         StringBuilder builder = new StringBuilder();
        for(Usluge u:this.order.usluge){
            builder.append(u.getNazivUsluge() +" "+u.getCijenaUsluge()+ "\n");
        }
        txtNarudzba.setText(builder.toString());
    }
    private void uslugeListActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_uslugeListActionPerformed
        // TODO add your handling code here:
     
        Usluge u = (Usluge)this.uslugeList.getSelectedItem();
        this.order.dodajUslugu(u);
        
        ispisiNarudzbu();
       
       
    }//GEN-LAST:event_uslugeListActionPerformed

    private void btnPotvrdaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnPotvrdaActionPerformed
        // TODO add your handling code here:
        if(this.order.getKlijent() == -1 || this.order.usluge.size() == 0)
            return;
        
        db.unosNarudzbe(order);
        
    }//GEN-LAST:event_btnPotvrdaActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(UnosNarudzbe.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(UnosNarudzbe.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(UnosNarudzbe.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(UnosNarudzbe.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new UnosNarudzbe().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnIzmjena;
    private javax.swing.JButton btnOdustani;
    private javax.swing.JButton btnPotvrda;
    private javax.swing.JComboBox<Klijent> clientList;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextArea txtNarudzba;
    private javax.swing.JComboBox<Usluge> uslugeList;
    // End of variables declaration//GEN-END:variables

   
}
